finos/legend-depot

checkstyle.xml
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/AdminServicesModule.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/ReadOnlyServicesModule.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/entities/EntitiesService.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/entities/EntityClassifierService.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/entities/EntityClassifierServiceImpl.java
legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java
legend-depot-server/Dockerfile
legend-depot-server/pom.xml
legend-depot-server/src/main/java/org/finos/legend/depot/server/guice/DepotServerResourcesModule.java
legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/dependencies/DependenciesResource.java
legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/entities/EntitiesResource.java
legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/entities/EntityClassifierResource.java
legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/file/FileGenerationsResource.java
legend-depot-store-api/src/main/java/org/finos/legend/depot/store/api/entities/Entities.java
legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java
legend-depot-store-server/Dockerfile

Closes https://github.com/finos/legend-depot/issues/20
We created an API **(labelled as WIP)** which
```json
{
"_type": "lambda",
"body": [
{
"_type": "func",
"function": "getAll",
"parameters": [
{
"_type": "packageableElementPtr",
"fullPath": "meta::pure::metamodel::type::Class"
}
]
}
],
"parameters": []
}
```
At first we thought we could be fancy and support lambda of form `DataSpace.all()->filter(s|$s.path->contains(<string>))->take(<limit>)` and the search will only limit to latest release of all the projects. But this is not possible with the current way entities are stored in `depot` as entities of **all** versions are stored. As such, either we invest more time (and space) to create another Mongo collection to store entities from the latest versions or alter the model of …

Create endpoint to query entities by classifier path

---

legend-depot-core-http/pom.xml
legend-depot-core-http/src/main/java/org/finos/legend/depot/core/http/BaseServer.java
pom.xml

This PR allows the server's configuration file to refer to environment variables. This allows for dynamic configuration such as Gitlab configuration values to be injected at runtime (via the environment).

Enable variable substitution with environment variables

---

legend-depot-server/pom.xml

The depot-server module is missing the runtime dependency.

Add pac4j gitlab dependency

---

legend-depot-server/pom.xml
legend-depot-store-server/pom.xml

This PR modifies the shading to include the shaded jar as a separate artifact. 
Without shadedArtifactAttached=true, the main jar becomes the shaded jar. However the Dockerfiles use a wildcard that refers to  ```*shaded.jar```.
This fixes the Dockerfile's CLASSPATH and also makes the shading configuration (more) consistent with the other Legend projects.

Included shaded jar as a separate artifact

---

.github/workflows/docker.yml
legend-depot-server/Dockerfile
legend-depot-store-server/Dockerfile

This PR disables the docker workflow from being globally run for all PRs.
Instead the action is run only if the PR changes the Dockerfile.
We are doing this because many of the CVEs do not have simple fixes and all the PRs are reported as failing a PR check.

Updating image scan workflow trigger

---

legend-depot-core-http/src/main/java/org/finos/legend/depot/core/http/BaseServer.java

Previously, we use `depot` `mongo` store for storing `userSessions` instead of using pac4j dedicated mongo store. This causes SSO to not work properly with `depot` and `depot store` servers

properly use pac4j mongo configurations

---

legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/entities/EntitiesService.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/entities/EntityClassifierService.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/projects/ProjectsService.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/entities/EntitiesServiceImpl.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/entities/EntityClassifierServiceImpl.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
legend-depot-model/src/main/java/org/finos/legend/depot/domain/project/ProjectVersion.java
legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/entities/EntityClassifierResource.java
legend-depot-store-api/src/main/java/org/finos/legend/depot/store/api/entities/Entities.java
legend-depot-store-api/src/main/java/org/finos/legend/depot/store/api/projects/Projects.java
legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/BaseMongo.java
legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java
legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/projects/ProjectsMongo.java
legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/entities/TestQueryClassifierPath.java
legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/entities/TestUpdateRevisions.java
legend-depot-store-mongo/src/test/resources/data/classifiers.json

Push the burden of performance onto `mongo` rather than trying to fetch all entities in `mongo` and then filter afterwards. The previous approach puts a heavy burden on memory (my past mistake here 😢), now the `limit` is pushed all the way to `mongo` layer which will expect to yield better performance overall

improve performance for entitiesByClassifier API

---

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java

Fix the regression introduced in https://github.com/finos/legend-depot/pull/117
We mistakenly cap the limit to `100` even when the `limit` is not specified

fix regression to entitiesByClassifier API with limit handling

---

legend-depot-server/Dockerfile
legend-depot-store-server/Dockerfile

It seems that `openjdk` no longer publish docker images for jdk11 - https://github.com/docker-library/openjdk/issues/505
So per their recommendation, we are trying out the alternative - `eclipse-temurin`

update java Docker image to `eclipse-temurin:11.0.17_8-jdk-jammy`

---

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/ArtifactsModule.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/api/ArtifactsRefreshService.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/api/status/RefreshStatusService.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/domain/status/RefreshStatus.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/resources/ArtifactsResource.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/store/mongo/MongoRefreshStatus.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshServiceExceptionEscenarios.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/store/mongo/TestMongoStatus.java
legend-depot-artifacts-repository-api/pom.xml
legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/RepositoryModule.java
legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/domain/VersionMismatch.java
legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/resources/RepositoryResource.java
legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/services/RepositoryServices.java
legend-depot-artifacts-repository-api/src/test/java/org/finos/legend/depot/artifacts/repository/services/TestVersionsMismatch.java
legend-depot-store-server/src/main/java/org/finos/legend/depot/store/server/LegendDepotStoreServer.java

Included in this PR:
- enhanced  versions mismatches api not fail in exception but rather expose that in the results. This might indicate there is an issue retrieving version from repository and need to be bubbled up.
- moved repository related apis to repository-api module and it own group in swagger. Functionally does not belong with the artifact refresh services.
- added ability to query refresh status by success or failure

fix-missing-versions-api

---

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/ArtifactsModule.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/api/ArtifactsRefreshService.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/domain/status/RefreshStatus.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/resources/ArtifactsResource.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactRefreshEventHandler.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/store/mongo/MongoRefreshStatus.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshServiceExceptionEscenarios.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/store/mongo/TestMongoStatus.java
legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/services/RepositoryServices.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/projects/ProjectsService.java
legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
legend-depot-model/src/main/java/org/finos/legend/depot/domain/project/ProjectData.java
legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/NotificationsModule.java
legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/api/NotificationsManager.java
legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/domain/MetadataNotification.java
legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/resources/NotificationsManagerResource.java
legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/services/NotificationsQueueManager.java
legend-depot-store-notifications/src/test/java/org/finos/legend/depot/store/notifications/services/TestNotificationManager.java
legend-depot-store-notifications/src/test/java/org/finos/legend/depot/store/notifications/store/mongo/TestQueueMongo.java

- leverage queue to scale and distribute refresh work
- introduce transitive flag so that dependencies are only updated transitively if true.
- when flag is false we check the dependency project had been previously loaded into store and raise an error otherwise

enhancements-to-refresh

---

legend-depot-artifacts-purge/pom.xml
legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/ArtifactsPurgeModule.java
legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/api/ArtifactsPurgeService.java
legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/resources/ArtifactsPurgeResource.java
legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java
legend-depot-artifacts-purge/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsPurgeService.java
legend-depot-artifacts-purge/src/test/resources/data/entities.json
legend-depot-artifacts-purge/src/test/resources/data/generations.json
legend-depot-artifacts-purge/src/test/resources/data/projects.json
legend-depot-artifacts-purge/src/test/resources/logback-test.xml
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/ArtifactsModule.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/ArtifactsRefreshModule.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/api/ArtifactsRefreshService.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/resources/ArtifactsRefreshResource.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactHandlerFactory.java
legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshServiceExceptionEscenarios.java
legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/domain/VersionMismatch.java
legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/services/RepositoryServices.java
legend-depot-artifacts-repository-api/src/test/java/org/finos/legend/depot/artifacts/repository/services/TestVersionsMismatch.java
legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java
legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/TestStoreMongo.java
legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/generation/file/TestFileGenerationsStore.java
legend-depot-store-server/pom.xml
legend-depot-store-server/src/main/java/org/finos/legend/depot/store/server/LegendDepotStoreServer.java
legend-depot-store-server/src/main/resources/authorisedIdentities.json
pom.xml

- separated artifacts refresh functionality from purge
- purge old versions has been moved to the new purge module and exposed in the resource
- purge can only invoked manually for now

retire old versions purge api

---

pom.xml

If one starts depot-store/depot server right now with client of type `org.finos.legend.server.pac4j.gitlab.GitlabClient`, one would see `ClassNotFoundException` for the class `LangTagException` which can be found in `com.nimbusds.lang-tag`, we might have accidentally excluded this.

unexclude com.nimbusds.lang-tag to avoid ClassNotFound exception when using Pac4j with Gitlab

---

legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/resources/NotificationsManagerResource.java

Currently, Swagger assumes the API for `/queue` returns a JSON, but in fact, it returns a string, this is the correction for that.

minor API swagger fix

---

legend-depot-store-metrics/src/main/java/org/finos/legend/depot/store/metrics/MetricsModule.java

configure persist metrics schedule to be delayed to avoid concurrency errors

configure persist metrics schedule to be delayed to avoid concurrency errors

---

legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/ProjectsVersionsResource.java

fixing "Could not resolve pointer" error for versions resource in swagger resource

fixing "Could not resolve pointer" error for versions resource in swagger resource

---

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java
legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java

evicted snapshot versions should not be refreshed

Stop refreshing snapshot versions which are evicted

---

legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java
legend-depot-entities-services/src/main/java/org/finos/legend/depot/server/resources/entities/EntitiesResource.java
legend-depot-entities-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/AbstractEntitiesMongo.java
legend-depot-entities-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/entities/TestQueryVersions.java

Skips package filter when package not defined to save on possibly expensive regex matching. This changes behaviour in that if a package is not defined, we will retrieve all entities as opposed to no entities.
Improve efficiency of classifier filtering by executing filter on db index instead of in memory filter.
Clarify entities by package api description.
Optimizes imports.

Optimize entity retrieval with classifier filters

---

legend-depot-core-data-api/src/main/java/org/finos/legend/depot/services/api/projects/ProjectsService.java
legend-depot-core-data-api/src/main/java/org/finos/legend/depot/store/api/projects/ProjectsVersions.java
legend-depot-core-data-api/src/main/java/org/finos/legend/depot/store/model/projects/StoreProjectVersionData.java
legend-depot-core-data-services/src/main/java/org/finos/legend/depot/server/resources/versions/ProjectsVersionsResource.java
legend-depot-core-data-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
legend-depot-core-data-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/projects/ProjectsVersionsMongo.java
legend-depot-core-data-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/projects/TestQueryProjectVersionApi.java
legend-depot-core-data-store-mongo/src/test/resources/data/projectsVersions.json
legend-depot-core-tracing/src/main/java/org/finos/legend/depot/core/services/tracing/ResourceLoggingAndTracing.java

New Projects Versions Endpoint
/projects/versions/{createdFrom time in UTC milliseconds}?{createdTo end time in milliseconds in UTC}
to query for changed versions from a created from time limited possible by a created to time to enable querying for continuous change streams over time thereby reducing return load on the depot server as well as reducing processing for the client.
The times are specified in milliseconds and will be treated as UTC timestamps

New Endpoint - Querying project versions by creation date

---

legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/artifacts/refresh/RefreshDependenciesServiceImpl.java
legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/refresh/TestRefreshDependenciesService.java
legend-depot-core-data-api/src/main/java/org/finos/legend/depot/domain/project/dependencies/ProjectDependencyGraphWalkerContext.java
legend-depot-core-data-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
legend-depot-core-data-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java

There are two places which needed this change:
1. Reporting conflicts as part of project graph
2. Calculating transitive dependencies for a version for storage

fix dependency resolution for overriding dependencies

---

legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/artifacts/handlers/generations/FileGenerationHandlerImpl.java
legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/handlers/generations/TestGenerationsProvider.java

Fix bug so that generated files don't end up with elementPath pointing to wrong entity. Specifically, ensure that generated files don't end up with elementPath that is only a prefix of the actual elementPath.

Fix bug so that generated files don't end up with elementPath pointing to wrong entity

---

legend-depot-core-data-api/src/main/java/org/finos/legend/depot/services/api/EtagBuilder.java
legend-depot-entities-api/src/main/java/org/finos/legend/depot/services/api/entities/EntitiesService.java
legend-depot-entities-services/src/main/java/org/finos/legend/depot/server/resources/entities/EntitiesDependenciesResource.java
legend-depot-entities-services/src/main/java/org/finos/legend/depot/server/resources/entities/EntitiesResource.java
legend-depot-entities-services/src/main/java/org/finos/legend/depot/services/entities/EntitiesServiceImpl.java
legend-depot-entities-services/src/test/java/org/finos/legend/depot/services/entities/TestEntitiesService.java
legend-depot-entities-services/src/test/resources/data/PROD-B/entities-1.0.1.json
legend-depot-entities-services/src/test/resources/data/PROD-C/entities-2.0.2.json

add get project entities by classifier API

add get project entities by classifier API
