legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java
=> Fix error message for when project is not found

legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/dependencies/DependenciesResource.java
change "version" to "versions" in expound url
=> Change getProjectDependencies url to use common pattern

legend-depot-store-status/src/main/java/org/finos/legend/depot/store/status/resources/StatusStoreResource.java
=> Change getVersionCounts url to use common pattern

legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/generation/file/FileGenerationsService.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/generation/file/TestFileGenerationsService.java, legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/file/FileGenerationsResource.java
add file generation content service
=> add file generation content service

legend-depot-test-reports/pom.xml, pom.xml
Updating the Sonatype host and adding the nexus-staging-plugin
=> Updating Sonatype host

pom.xml
=> Update Legend dependencies

pom.xml
Update engine and sdlc versions
=> Update engine and sdlc versions

pom.xml
Update legend-engine and legend-sdlc versions
=> Update legend-engine and legend-sdlc versions

pom.xml
Upgrade to latest legend-engine and legend-sdlc
=> Upgrade to latest legend-engine and legend-sdlc

pom.xml
=> Update engine, sdlc versions

legend-depot-server/pom.xml, legend-depot-store-server/pom.xml
=> Revert "Included shaded jar as a separate artifact"

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/ArtifactsModule.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/api/ArtifactsRefreshService.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/api/status/RefreshStatusService.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/domain/status/RefreshStatus.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/domain/status/VersionMismatch.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/resources/ArtifactsResource.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/store/mongo/MongoRefreshStatus.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestVersionsMismatch.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/store/mongo/TestMongoStatus.java, legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/api/ArtifactRepositoryProviderConfiguration.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java, legend-depot-store-admin/src/main/java/org/finos/legend/depot/store/admin/services/schedules/SchedulesFactory.java, legend-depot-store-server/src/test/resources/sample-server-config.json, legend-depot-store-status/src/main/java/org/finos/legend/depot/store/status/StoreStatusModule.java, legend-depot-store-status/src/main/java/org/finos/legend/depot/store/status/domain/StoreStatus.java, legend-depot-store-status/src/main/java/org/finos/legend/depot/store/status/resources/StatusStoreResource.java, legend-depot-store-status/src/main/java/org/finos/legend/depot/store/status/services/StoreStatusService.java, legend-depot-store-status/src/test/java/org/finos/legend/depot/store/status/TestStatusServices.java
- moving version mismatch function to artifacts module 
-  scheduling a deamon that will periodically attempt to fix version mismatches
- adding the ability to search by start time in refresh status data
=> fix-versions-mismatch

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/ArtifactsModule.java, legend-depot-store-admin/src/main/java/org/finos/legend/depot/store/admin/StoreAdminModule.java, legend-depot-store-admin/src/main/java/org/finos/legend/depot/store/admin/api/ManageSchedulesService.java, legend-depot-store-admin/src/main/java/org/finos/legend/depot/store/admin/resources/AdminResource.java, legend-depot-store-admin/src/main/java/org/finos/legend/depot/store/admin/resources/SchedulesResource.java, legend-depot-store-admin/src/main/java/org/finos/legend/depot/store/admin/services/schedules/SchedulesFactory.java, legend-depot-store-admin/src/main/java/org/finos/legend/depot/store/admin/store/mongo/MongoSchedules.java, legend-depot-store-admin/src/test/java/org/finos/legend/depot/store/admin/services/TestSchedules.java, legend-depot-store-server/src/main/resources/authorisedIdentities.json
separating the refresh apis and fixin bug on toggle disable
=> versions-api-refresh

README.md, legend-depot-artifacts-refresh/README.md, legend-depot-server/src/test/resources/sample-server-config.json, legend-depot-store-server/src/test/resources/sample-server-config.json
Also updated doc at https://github.com/finos/legend/pull/542
=> standardize Depot port to `62xx` range

legend-depot-server/Dockerfile, legend-depot-server/src/main/resources/docker/config/config.json, legend-depot-store-server/Dockerfile, legend-depot-store-server/src/main/resources/docker/config/authorisedIdentities.json, legend-depot-store-server/src/main/resources/docker/config/config.json, legend-depot-store-server/src/main/resources/docker/config/settings.xml
Add default config files to Docker image
=> Add default config files to Docker image

legend-depot-server/Dockerfile, legend-depot-store-server/Dockerfile
=> Fix classpath wildcard

legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-model/src/main/java/org/finos/legend/depot/domain/EntityValidator.java, legend-depot-model/src/test/java/org/finos/legend/depot/domain/project/TestProjectValidator.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/projects/ProjectsMongo.java
make groupid/artifactid validation consistent with sdlc
=> Group id validation

legend-depot-core-http/src/main/java/org/finos/legend/depot/core/http/BaseServer.java, legend-depot-core-http/src/main/java/org/finos/legend/depot/core/http/ServersConfiguration.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/AdminServicesModule.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/ReadOnlyServicesModule.java, legend-depot-server/src/main/java/org/finos/legend/depot/server/LegendDepotServer.java, legend-depot-server/src/test/resources/sample-server-config.json, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/ManageMongoModule.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/ReadMongoModule.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/server/LegendDepotStoreServer.java, legend-depot-store-server/src/test/resources/sample-server-config.json
- Refactor Mongo store injection
- Pick URL pattern from config
=> Refactor mongo store injection and pick url pattern from config

legend-depot-artifacts-purge/pom.xml, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/ArtifactsPurgeModule.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/api/ArtifactsPurgeService.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/resources/ArtifactsPurgeResource.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java, legend-depot-artifacts-purge/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsPurgeService.java, legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/api/ArtifactRepositoryProviderConfiguration.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java, legend-depot-store-server/src/main/resources/docker/config/config.json, legend-depot-store-server/src/test/resources/sample-server-config.json
delete all versions not present in repository and cleanup version mismatches using schedule
=> delete all versions not present in repository and cleanup version mismatches using schedule

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/core/BaseMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/generation/file/FileGenerationsMongo.java, legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/admin/TestMongoAdminStore.java
Support creation of unique indexes especially while storing entities and file generation
=> Support creation of unique indexes

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/MongoAdminStore.java
fix bug and include file generations mongo indexes
=> fix bug and include file generations mongo indexes

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/core/BaseMongo.java
=> fix bug for creating indexes

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshServiceViaMock.java
fix bug while refreshing project versions with master snapshot dependencies
=> fix bug while refreshing project versions with master snapshot dependencies

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/services/TracerFactory.java
=> Fix refresh exceptions msg

legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/projects/ProjectsService.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java, legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/ProjectsResource.java, legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/ProjectsVersionsResource.java, legend-depot-store-api/src/main/java/org/finos/legend/depot/store/api/projects/Projects.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/projects/ProjectsMongo.java, legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/projects/TestQueryProjectApi.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/resources/projects/ManageProjectsResource.java
add API for getting all projects data for backward compatibility
=> add API for getting all projects data for backward compatibility

legend-depot-server/src/main/resources/docker/config/config.json, legend-depot-store-server/src/main/resources/docker/config/config.json
Update default Docker config.json with server url parameter
=> Update default Docker config.json with server url parameter

legend-depot-store-mongo/README.md
add documentation for the migration of project data
=> add documentation for the migration of project data

legend-depot-store-mongo/README.md
fix indentation for documentation
=> fix indentation for documentation

legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/api/ArtifactsPurgeService.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/resources/ArtifactsPurgeResource.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java, legend-depot-artifacts-purge/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsPurgeService.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java
[provide apis for both eviction and deletion of gav
=> provide apis for both eviction and deletion of gav

legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/projects/ProjectsService.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java, legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/ProjectsVersionsResource.java, legend-depot-server/src/test/java/org/finos/legend/depot/server/TestProjectsVersionsResource.java
support querying version data of latest version using the project version API
=> support querying version data of latest version using the project version API

legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/ProjectsResource.java, legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/ProjectsVersionsResource.java, legend-depot-server/src/test/java/org/finos/legend/depot/server/TestProjectsResource.java, legend-depot-server/src/test/java/org/finos/legend/depot/server/TestProjectsVersionsResource.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/guice/DepotStoreResourcesModule.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/resources/projects/ManageProjectsResource.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/resources/versions/ManageProjectsVersionsResource.java, legend-depot-store-server/src/main/resources/authorisedIdentities.json
Change API paths for versions resources
=> Change API paths for versions resources

legend-depot-model/src/main/java/org/finos/legend/depot/domain/notifications/EventPriority.java, legend-depot-model/src/main/java/org/finos/legend/depot/domain/notifications/MetadataNotification.java, legend-depot-store-api/src/main/java/org/finos/legend/depot/store/admin/domain/artifacts/RefreshStatus.java, legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/services/NotificationsQueueManager.java, legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/store/mongo/NotificationsQueueMongo.java, legend-depot-store-notifications/src/test/java/org/finos/legend/depot/store/notifications/store/mongo/TestQueueMongo.java
Handle events with respect to the priority of the notifications
=> Handle events with respect to the priority of the notifications

legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java
adding more logs for deletion and eviction
=> adding more logs for deletion and eviction

pom.xml
Upgrade Engine and SDLC versions
=> Upgrade Engine and SDLC versions

legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/ArtifactsPurgeModule.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/api/ArtifactsPurgeService.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/resources/ArtifactsPurgeResource.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java, legend-depot-artifacts-purge/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsPurgeService.java, legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/api/ArtifactRepositoryProviderConfiguration.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java, legend-depot-model/src/main/java/org/finos/legend/depot/domain/project/ProjectVersionData.java, legend-depot-store-server/src/main/resources/docker/config/config.json, legend-depot-store-server/src/test/resources/sample-server-config.json
remove support for deleting artifacts not present in the repository (schedule and API)
=> remove support for deleting artifacts not present in the repository

legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-model/src/main/java/org/finos/legend/depot/domain/project/dependencies/ProjectDependencyGraphWalkerContext.java
fix bugs for dependency conflicts while analyzing dependencies
=> fix bugs for dependency conflicts while analyzing dependencies

legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/DependenciesCache.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestDependencyCache.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-pure-model-context/src/test/java/org/finos/legend/depot/server/pure/model/context/TestPureModelContextService.java
fix initializing dependency cache ensure we don't store missing dependencies in the store.
=> fix initializing dependency cache

legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java, legend-depot-server/src/main/java/org/finos/legend/depot/server/resources/ProjectsResource.java
add API for fetching project configuration by ga
=> add API for fetching project configuration by ga

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ProjectVersionRefreshHandler.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestProjectVersionRefreshHandler.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/projects/ManageProjectsService.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ManageProjectsServiceImpl.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/resources/ResourceLoggingAndTracing.java, legend-depot-model/src/main/java/org/finos/legend/depot/domain/project/ProjectVersionData.java, legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/services/NotificationsQueueManager.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/resources/versions/ManageProjectsVersionsResource.java
add a workflow to deal with versions that cannot be loaded in the store
=> add a workflow to deal with versions that cannot be loaded in the store

pom.xml
update engine to 4.5.0 and sdlc to 0.122.2
=> update engine to 4.5.0 and sdlc to 0.122.2

legend-depot-core-schedules/src/main/java/org/finos/legend/depot/schedules/resources/SchedulesResource.java
adding a note to what toggle means for disabling resources
=> adding a note to what toggle means for disabling schedules

legend-depot-core-tracing/src/main/java/org/finos/legend/depot/tracing/services/prometheus/DepotPrometheusMetricsHandler.java
easier to group and identify api related metrics
=> add api to Prometheus metric name

legend-depot-store-mongo/README.md, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/MongoAdminStore.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/migrations/DependenciesMigration.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/resources/StoreAdministrationResource.java, legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/admin/migrations/TestDependenciesMigration.java
changes to speed up the dependencies migration process
=> Migration of transitive dependencies to store

pom.xml
Upgrade legend-engine and legend-sdlc versions to 4.9.0 and 0.125.0, respectively
=> Upgrade legend-engine and legend-sdlc versions

legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java
=> better implementation for find latest version

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/migrations/ProjectToProjectVersionMigration.java
cleaning project data by unsetting fields and updating documents
=> cleaning project data by unsetting fields and updating documents

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ProjectVersionRefreshHandler.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/projects/ProjectsService.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/generation/file/ManageFileGenerationsServiceImpl.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java
Cleaning up checking existence of project versions and resolving aliases
=> Cleaning up checking existence of project versions and resolving aliases

pom.xml
Updating engine to 4.11.1 and sdlc to 0.127.1
=> Update engine to 4.11.1 and sdlc to 0.127.1

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/ArtifactsRefreshModule.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/configuration/ArtifactsRetentionPolicyConfiguration.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ProjectVersionRefreshHandler.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshServiceExceptionEscenarios.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshServiceWithMocks.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestDependencyManager.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestProjectVersionRefreshHandler.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/projects/ProjectsService.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/guice/DepotStoreServerModule.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/server/configuration/DepotStoreServerConfiguration.java, legend-depot-store-server/src/main/resources/docker/config/config.json
limiting snapshot versions of projects
=> limiting storage and processing snapshot versions of projects

legend-depot-store-api/src/main/java/org/finos/legend/depot/store/admin/api/metrics/QueryMetricsStore.java, legend-depot-store-metrics/src/main/java/org/finos/legend/depot/store/metrics/MetricsModule.java, legend-depot-store-metrics/src/main/java/org/finos/legend/depot/store/metrics/resources/StoreMetricsResource.java, legend-depot-store-metrics/src/main/java/org/finos/legend/depot/store/metrics/services/QueryMetricsHandler.java, legend-depot-store-metrics/src/test/java/org/finos/legend/depot/store/metrics/TestMetricsServices.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/metrics/QueryMetricsMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/metrics/VoidQueryMetricsStore.java
adding schedule to consolidate query metrics
=> adding schedule to consolidate query metrics

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/metrics/VoidQueryMetricsStore.java
fix injection of VoidQueryMetricsStore dependency
=> fix injection of VoidQueryMetricsStore dependency

legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/ArtifactsPurgeModule.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/api/ArtifactsPurgeService.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java, legend-depot-artifacts-purge/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsPurgeService.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/configuration/ArtifactsRetentionPolicyConfiguration.java, legend-depot-store-api/src/main/java/org/finos/legend/depot/store/admin/api/metrics/QueryMetricsStore.java, legend-depot-store-metrics/src/main/java/org/finos/legend/depot/store/metrics/services/QueryMetricsHandler.java, legend-depot-store-metrics/src/main/java/org/finos/legend/depot/store/metrics/store/VoidQueryMetricsStore.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/metrics/QueryMetricsMongo.java, legend-depot-store-server/src/main/resources/docker/config/config.json
implementing retention policy for project versions artifacts
=> implementing retention policy for project versions artifacts

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ProjectVersionRefreshHandler.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
version handler to only check if project version exists
We don't want to resolve the alias as part of that check
=> version handler to only check if project version exists

legend-depot-artifacts-repository-maven-impl/src/main/java/org/finos/legend/depot/artifacts/repository/maven/impl/MavenArtifactRepository.java
resolve pom without transitivity in maven artifact repository
=> resolve pom without transitivity in maven artifact repository

pom.xml
This reverts commit 4b1c6580Revert "Upgrade engine, sdlc versions (#300)"
=> Revert "Upgrade engine, sdlc versions (#300)"

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ProjectVersionRefreshHandler.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestProjectVersionRefreshHandler.java
refresh already registered snapshots irrespective of snapshot storage quota
=> refresh already registered snapshots irrespective of snapshot storage quota

pom.xml
=> Revert "Legend Stack Update"

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java, legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/entities/TestUpdateVersions.java, legend-depot-store-mongo/src/test/resources/data/versioned-entity-dot-character.json
using update options to create or incrementally update entities
=> Using update options to create or incrementally update entities

legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/ArtifactsPurgeModule.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/api/ArtifactsPurgeService.java, legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java, legend-depot-artifacts-purge/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsPurgeService.java
auto-deprecate all versions not present in the repository
=> auto-deprecate all versions not present in the repository

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/file/FileGenerationHandlerImpl.java
=> fix style check error

legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestDependencyManager.java, legend-depot-artifacts-refresh/src/test/resources/data/projects.json, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
improving performance of API fetching dependent projects
=> improving performance of API fetching dependent projects

legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/NotificationsModule.java, legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/services/NotificationsQueueManager.java
adding priority label to notifications complete metric
=> adding priority label to notifications complete metric

legend-depot-store-notifications/src/main/java/org/finos/legend/depot/store/notifications/services/NotificationsQueueManager.java
adding label values to notification complete metric
=> adding label values to notification complete metric

legend-depot-model/src/main/java/org/finos/legend/depot/domain/entity/StoredEntity.java, legend-depot-model/src/main/java/org/finos/legend/depot/domain/entity/StoredVersionedEntity.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/AbstractEntitiesMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java, legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/admin/migrations/TestVersionedEntitiesMigration.java
Ensuring stored entities are backward compatible
=> Ensuring stored entities are backward compatible

legend-depot-pure-model-context/src/test/resources/versioned-entities_PROD-10357.json, legend-depot-pure-model-context/src/test/resources/versioned-entities_PROD-10855.json, legend-depot-pure-model-context/src/test/resources/versioned-entities_PROD-16538.json, legend-depot-store-mongo/README.md, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/AbstractEntitiesMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/versionedEntities/VersionedEntitiesMongo.java, legend-depot-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/admin/TestMongoAdminStore.java
Implementing safeguards for migration of versioned entities
=> Implementing safeguards for migration of versioned entities

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/api/ArtifactsRefreshService.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/resources/ArtifactsRefreshResource.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ArtifactsRefreshServiceImpl.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java
refreshing only default branch snapshots for schedules
=> refreshing only default branch snapshots for schedules

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/migrations/EntitiesMigration.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/AbstractEntitiesMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/versionedEntities/VersionedEntitiesMongo.java
increasing performance for entities migration
=> increasing performance for entities migration

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java
renaming indexes for entities mongo
=> renaming indexes for entities mongo

legend-depot-pure-model-context/src/main/java/org/finos/legend/depot/server/pure/model/context/services/PureModelContextServiceImpl.java, legend-depot-pure-model-context/src/test/java/org/finos/legend/depot/server/pure/model/context/TestPureModelContextService.java
Adding validity check for client versions while fetching PMCD
=> Adding validity check for client versions while fetching PMCD

legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/AbstractEntitiesMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/versionedEntities/VersionedEntitiesMongo.java
increasing performance for serialization and deserialization of entities
=> increasing performance for serialization and deserialization of entities

legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java, legend-depot-artifacts-purge/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsPurgeService.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ProjectVersionRefreshHandler.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshServiceExceptionEscenarios.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshServiceWithMocks.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestDependencyManager.java, legend-depot-artifacts-repository-api/pom.xml, legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/RepositoryModule.java, legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/resources/RepositoryResource.java, legend-depot-artifacts-repository-api/src/main/java/org/finos/legend/depot/artifacts/repository/services/RepositoryServices.java, legend-depot-core-services/pom.xml, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/ManageServicesModule.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/VersionsMismatchService.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/TestVersionsMismatchService.java, legend-depot-model/src/main/java/org/finos/legend/depot/domain/version/VersionMismatch.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/resources/versions/ManageProjectsVersionsResource.java
refactor code to separate repository from core services
=> Separate repository services from projects

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/ArtifactsRefreshModule.java, legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ProjectVersionRefreshHandler.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestArtifactsRefreshService.java, legend-depot-artifacts-refresh/src/test/java/org/finos/legend/depot/store/artifacts/services/TestProjectVersionRefreshHandler.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/ManageServicesModule.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/ReadDataServicesModule.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/api/dependencies/ManageDependenciesService.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/dependencies/DependencyUtil.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/dependencies/ManageDependenciesServiceImpl.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ManageProjectsServiceImpl.java, legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/dependencies/TestManageDependenciesService.java, legend-depot-core-services/src/test/resources/data/testProjects.json, legend-depot-core-services/src/test/resources/data/testProjectsVersions.json, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/guice/DepotStoreResourcesModule.java, legend-depot-store-server/src/main/java/org/finos/legend/depot/store/resources/dependencies/ManageDependenciesResource.java
overriding transitive dependencies by the root dependencies
=> Overriding transitive dependencies by the root dependencies

legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-model/src/main/java/org/finos/legend/depot/domain/project/dependencies/ProjectDependencyReport.java
override dependencies on conflicts as part of project dependency report
=> override dependencies on conflicts as part of project dependency report

legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/guice/ArtifactsRefreshModule.java, legend-depot-core-schedules/src/main/java/org/finos/legend/depot/services/schedules/SchedulesFactory.java, legend-depot-core-schedules/src/main/java/org/finos/legend/depot/store/resources/schedules/SchedulesResource.java
adding a workflow to maintain information about external schedules
=> adding a workflow to maintain information about external schedules

legend-depot-core-data-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-data-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-entities-services/src/test/java/org/finos/legend/depot/services/entities/TestEntitiesService.java
overriding both transitive and direct dependencies
=> overriding both transitive and direct dependencies

pom.xml
update legend sdlc to 0.141.0 , legend engine to 4.25.2 and legend shared to 0.24.0
=> update legend versions

pom.xml
Update engine to 4.28.0 and sdlc to 0.144.0
=> Update engine to 4.28.0 and sdlc to 0.144.0

legend-depot-server/src/main/resources/docker/config/config.json, legend-depot-server/src/test/resources/sample-server-config.json, legend-depot-servers-common/src/main/java/org/finos/legend/depot/core/http/ServersConfiguration.java, legend-depot-servers-common/src/main/java/org/finos/legend/depot/core/http/guice/BaseModule.java, legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/core/MongoClientModule.java, legend-depot-store-server/src/main/resources/docker/config/config.json, legend-depot-store-server/src/test/resources/sample-server-config.json
implementing configuration for multiple storages
=> implementing configuration for multiple storages

legend-depot-core-data-services/src/main/java/org/finos/legend/depot/services/dependencies/ManageDependenciesServiceImpl.java, legend-depot-core-data-services/src/test/java/org/finos/legend/depot/services/dependencies/TestManageDependenciesService.java
bug fix for overriding dependencies while storing version data
=> bug fix for overriding dependencies while storing version data

pom.xml
Update legend-engine@4.29.0 and legend-sdlc @0.145.0
=> Update legend-engine@4.29.0 and legend-sdlc @0.145.0

legend-depot-generations-api/src/main/java/org/finos/legend/depot/store/api/generations/FileGenerations.java, legend-depot-generations-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/generations/FileGenerationsMongo.java, legend-depot-generations-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/generations/TestFileGenerationsStore.java
cleanup duplicate API in file generations store implementation
=> cleanup duplicate API in file generations store implementation

legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/artifacts/refresh/ProjectVersionRefreshHandler.java, legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/purge/TestArtifactsPurgeService.java, legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/refresh/TestArtifactsRefreshService.java, legend-depot-artifacts-services/src/test/resources/data/projects.json, legend-depot-core-data-api/src/main/java/org/finos/legend/depot/services/api/projects/ProjectsService.java, legend-depot-core-data-api/src/main/java/org/finos/legend/depot/store/api/projects/Projects.java, legend-depot-core-data-api/src/main/java/org/finos/legend/depot/store/model/projects/StoreProjectData.java, legend-depot-core-data-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-data-services/src/main/java/org/finos/legend/depot/store/resources/projects/ManageProjectsResource.java, legend-depot-core-data-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java, legend-depot-core-data-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/CoreDataMigrations.java, legend-depot-core-data-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/migrations/ProjectToProjectVersionMigration.java, legend-depot-core-data-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/projects/ProjectsMongo.java, legend-depot-core-data-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/resources/CoreDataStoreMigrationsResource.java, legend-depot-core-data-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/admin/migrations/TestProjectVersionMigrations.java, legend-depot-core-data-store-mongo/src/test/resources/data/projects.json, legend-depot-entities-services/src/main/java/org/finos/legend/depot/services/entities/EntityClassifierServiceImpl.java, legend-depot-entities-services/src/test/java/org/finos/legend/depot/services/entities/TestEntitiesService.java, legend-depot-generations-services/src/test/java/org/finos/legend/depot/services/generations/TestFileGenerationsService.java, legend-depot-pure-model-context/src/test/java/org/finos/legend/depot/services/pure/model/context/TestPureModelContextService.java, legend-depot-store-mongo/README.md
Storing latest version to project data
Removing the pagination of projects data
=> Storing latest version to project data

legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/guice/ArtifactsServicesModule.java
fix dependency injection for ArtifactsServiceModule
=> fix dependency injection for ArtifactsServiceModule

pom.xml
bump legend-engine and legend-sdlc version
=> bump legend-engine and legend-sdlc version

legend-depot-core-data-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java, legend-depot-core-data-services/src/test/java/org/finos/legend/depot/services/projects/TestProjectsService.java
return optional empty for projects which have no latest version
=> fix bug while finding latest version for projects

legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/artifacts/refresh/ProjectVersionRefreshHandler.java, legend-depot-core-data-api/src/main/java/org/finos/legend/depot/store/model/projects/StoreProjectData.java, legend-depot-core-data-api/src/test/java/org/finos/legend/depot/domain/project/TestProjectUtilities.java
* add logic to determine latest version of a project
* update project data only if there is change
* rename file and test the evaluation and update of latestVersion
=> fix bug while calculating latest version for project data storage

legend-depot-entities-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/AbstractEntitiesMongo.java, legend-depot-entities-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/entities/TestQueryClassifierPath.java
fix bug for querying classifiers by versions
=> fix bug for querying classifiers by versions

legend-depot-core-data-services/src/main/java/org/finos/legend/depot/server/resources/dependencies/DependenciesResource.java, legend-depot-core-data-services/src/main/java/org/finos/legend/depot/server/resources/projects/ProjectsResource.java, legend-depot-core-data-services/src/main/java/org/finos/legend/depot/server/resources/versions/ProjectsVersionsResource.java, legend-depot-core-data-services/src/test/java/org/finos/legend/depot/server/resources/TestProjectsResource.java, legend-depot-core-data-services/src/test/java/org/finos/legend/depot/server/resources/TestProjectsVersionsResource.java, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/core/services/tracing/resources/TracingResource.java, legend-depot-entities-services/src/main/java/org/finos/legend/depot/server/resources/entities/EntitiesDependenciesResource.java, legend-depot-entities-services/src/main/java/org/finos/legend/depot/server/resources/entities/EntityClassifierResource.java
return responses for depot server resources
=> Return responses for depot server resources

legend-depot-core-data-services/src/main/java/org/finos/legend/depot/server/resources/projects/ProjectsResource.java
adding response details for the versions api
=> adding response details for the versions api

pom.xml
=> Update engine and sdlc

legend-depot-core-tracing/src/main/java/org/finos/legend/depot/core/services/tracing/ResourceLoggingAndTracing.java, legend-depot-entities-api/src/main/java/org/finos/legend/depot/services/api/entities/EntitiesService.java, legend-depot-entities-api/src/main/java/org/finos/legend/depot/store/api/entities/Entities.java, legend-depot-entities-services/src/main/java/org/finos/legend/depot/server/resources/entities/EntitiesDependenciesResource.java, legend-depot-entities-services/src/main/java/org/finos/legend/depot/services/entities/EntitiesServiceImpl.java, legend-depot-entities-services/src/test/java/org/finos/legend/depot/services/entities/TestEntitiesService.java, legend-depot-entities-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/AbstractEntitiesMongo.java
adding new API to get an entity from a given projects dependencies
=> adding new API to get an entity from a given projects dependencies

pom.xml
Upgrade legend-engine to 4.39.0 and legend-sdlc to 0.156.0
=> Upgrade legend-engine@4.39.0 and legend-sdlc@0.156.0

pom.xml
Upgrade legend-engine to 4.39.1 and legend-sdlc to 0.156.1
=> Upgrade legend-engine@4.39.1 and legend-sdlc@0.156.1

legend-depot-entities-api/src/main/java/org/finos/legend/depot/services/api/entities/EntityClassifierService.java, legend-depot-entities-api/src/main/java/org/finos/legend/depot/store/api/entities/Entities.java, legend-depot-entities-services/src/main/java/org/finos/legend/depot/server/resources/entities/EntityClassifierResource.java, legend-depot-entities-services/src/main/java/org/finos/legend/depot/services/entities/EntityClassifierServiceImpl.java, legend-depot-entities-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/AbstractEntitiesMongo.java, legend-depot-entities-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/entities/EntitiesMongo.java, legend-depot-entities-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/entities/TestQueryClassifierPath.java, legend-depot-entities-store-mongo/src/test/java/org/finos/legend/depot/store/mongo/entities/TestQueryRevisions.java, legend-depot-generations-services/src/main/java/org/finos/legend/depot/services/generations/impl/FileGenerationsServiceImpl.java
refactor and decompose classifier APIs functionally
improve performance of APIs
decouple different functionalities related to classifier API
=> refactor and decompose classifier APIs functionally

legend-depot-core-tracing/src/main/java/org/finos/legend/depot/core/services/tracing/ResourceLoggingAndTracing.java, legend-depot-pure-model-context/src/main/java/org/finos/legend/depot/server/resources/pure/model/context/PureModelContextResource.java, legend-depot-pure-model-context/src/main/java/org/finos/legend/depot/services/api/pure/model/context/PureModelContextService.java, legend-depot-pure-model-context/src/main/java/org/finos/legend/depot/services/pure/model/context/PureModelContextServiceImpl.java, legend-depot-pure-model-context/src/test/java/org/finos/legend/depot/server/resources/TestPureModelContextDataResource.java, legend-depot-pure-model-context/src/test/resources/allProjectVersions.json, legend-depot-pure-model-context/src/test/resources/versioned-entities-allProjects.json
New API for getting PMCD for multiple GAVs
=> New PMCD API for multiple ProjectVersion

pom.xml
engine @4.40.3 shared @ 0.25.4 sdlc@0.157.1
=> engine @4.40.3 shared @ 0.25.4 sdlc@0.157.1

pom.xml
Add dependency management for org.slf4j:jul-to-slf4j
=> Add dependency management for org.slf4j:jul-to-slf4j

legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/handlers/generations/TestGenerationsProvider.java, legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/purge/TestArtifactsPurgeService.java, legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/refresh/TestArtifactsRefreshService.java, legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/refresh/TestArtifactsRefreshServiceExceptionEscenarios.java, legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/refresh/TestArtifactsRefreshServiceWithMocks.java, legend-depot-generations-api/src/main/java/org/finos/legend/depot/services/api/generations/FileGenerationsService.java, legend-depot-generations-services/pom.xml, legend-depot-generations-services/src/main/java/org/finos/legend/depot/server/resources/generations/FileGenerationsResource.java, legend-depot-generations-services/src/main/java/org/finos/legend/depot/services/generations/impl/FileGenerationsServiceImpl.java, legend-depot-generations-services/src/main/java/org/finos/legend/depot/services/generations/impl/ManageFileGenerationsServiceImpl.java, legend-depot-generations-services/src/test/java/org/finos/legend/depot/services/generations/TestFileGenerationsService.java
cleanup generation API for entities
=> cleanup generation API for entities

legend-depot-core-data-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
fixing inconsistency issues for a non-concurrent data structure
=> fixing inconsistency issues for a non-concurrent data structure

pom.xml
Upgrade legend-engine to 4.47.2 and legend-sdlc to 0.163.1
=> Upgrade engine@4.47.2 and sdlc@0.163.1

pom.xml
Upgrade legend-engine to 4.47.3 and legend-sdlc 0.163.2
=> Upgrade engine@4.47.3 and sdlc@0.163.2

pom.xml
Update Engine@4.52.1 and SDLC@0.169.0
=> Update Engine@4.52.1 and SDLC@0.169.0

legend-depot-artifacts-api/src/main/java/org/finos/legend/depot/services/api/artifacts/reconciliation/VersionsReconciliationService.java, legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/artifacts/reconciliation/VersionsReconciliationServiceImpl.java, legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/guice/VersionReconciliationSchedulesModule.java, legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/reconciliation/TestVersionsMismatchService.java
Syncing projects' latest versions to latest non-evicted, non-excluded and non-deprecated store version if mismatch exists
=> Syncing projects' latest versions to latest non-evicted, non-excluded and non-deprecated store version if mismatch exists

pom.xml
Upgrade engine@4.53.8 and sdlc@0.171.3
=> Upgrade engine@4.53.8 and sdlc@0.171.3

pom.xml
Upgrade legend-shared@0.25.6, legend-engine@4.54.0 and legend-sdlc@0.172.0
=> Upgrade legend-shared@0.25.6, legend-engine@4.54.0 and legend-sdlc@0.172.0

pom.xml
=> Upgrade engine@4.54.1 and legend-sdlc@0.172.1

pom.xml
Update pom.xml for engine release
=> Update pom.xml for engine release

legend-depot-core-schedules-api/src/main/java/org/finos/legend/depot/store/api/admin/schedules/ScheduleInstancesStore.java, legend-depot-core-schedules-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/schedules/ScheduleInstancesMongo.java, legend-depot-core-schedules/src/main/java/org/finos/legend/depot/services/schedules/SchedulesFactoryImpl.java, legend-depot-core-schedules/src/test/java/org/finos/legend/depot/services/schedules/MockInstancesStore.java
refactor schedules to push down expired filter
=> refactor schedules to push down expired filter

legend-depot-entities-services/src/main/java/org/finos/legend/depot/server/resources/entities/EntitiesResource.java, legend-depot-entities-services/src/test/java/org/finos/legend/depot/server/resources/TestEntitiesResource.java
enable etag on latest version by resolving latest
=> enable etag on latest version by resolving latest

pom.xml
=> Update pom.xml for release

pom.xml
Update Engine to 4.62.0 and sdlc to 0.176.0
=> Update Engine to 4.62.0 and sdlc to 0.176.0

pom.xml
Upgrade legend-engine to 4.63.1, legend-sdlc to 0.177.0, and legend-shared to 0.25.7.
=> Upgrade engine@4.63.1, sdlc@0.177.0, and shared@0.25.7

pom.xml
Upgrade legend-engine to 4.63.2 and legend-sdlc to 0.177.3
=> Upgrade engine@4.63.2 and sdlc@0.177.3

pom.xml
legend-engine@4.67.4 and legend-sdlc@0.178.1
=> legend-engine@4.67.5 and legend-sdlc@0.178.2

legend-depot-pure-model-context/src/main/java/org/finos/legend/depot/services/pure/model/context/PureModelContextServiceImpl.java, legend-depot-server/src/test/resources/sample-server-config.json
fixing the legend depot server configuration
=> fixing the legend depot server configuration

legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/artifacts/purge/ArtifactsPurgeServiceImpl.java, legend-depot-metrics-query-api/src/main/java/org/finos/legend/depot/services/api/metrics/query/QueryMetricsService.java, legend-depot-metrics-query-api/src/main/java/org/finos/legend/depot/store/api/metrics/query/QueryMetrics.java, legend-depot-metrics-query-services/src/main/java/org/finos/legend/depot/services/metrics/query/QueryMetricsServiceImpl.java, legend-depot-metrics-query-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/metrics/query/QueryMetricsMongo.java, legend-depot-pure-model-context/src/main/java/org/finos/legend/depot/services/pure/model/context/PureModelContextServiceImpl.java, legend-depot-server/src/test/resources/sample-server-config.json, legend-depot-store-server/src/main/resources/docker/config/config.json, legend-depot-store-server/src/test/resources/sample-server-config.json
Add methods to delete query metrics
=> Add methods to delete query metrics

legend-depot-pure-model-context/src/main/java/org/finos/legend/depot/services/pure/model/context/PureModelContextServiceImpl.java, legend-depot-pure-model-context/src/test/java/org/finos/legend/depot/server/resources/TestPureModelContextDataResource.java, pom.xml
Protocol refactoring fix, update Engine @4.68.0, SDLC @0.180.0
=> Protocol refactoring fix, update Engine @4.68.0, SDLC @0.180.0

legend-depot-artifacts-api/src/main/java/org/finos/legend/depot/services/api/artifacts/purge/ArtifactsPurgeService.java, legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/artifacts/purge/ArtifactsPurgeServiceImpl.java, legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/store/resources/artifacts/ArtifactsPurgeResource.java, legend-depot-artifacts-services/src/test/java/org/finos/legend/depot/services/artifacts/purge/TestArtifactsPurgeService.java, legend-depot-artifacts-services/src/test/resources/data/entities.json, legend-depot-artifacts-services/src/test/resources/data/projectsVersions.json, legend-depot-core-tracing/src/main/java/org/finos/legend/depot/core/services/tracing/ResourceLoggingAndTracing.java
Add API to delete snapshot versions
=> Add API to delete snapshot versions

legend-depot-pure-model-context/src/main/java/org/finos/legend/depot/services/pure/model/context/PureModelContextServiceImpl.java, legend-depot-pure-model-context/src/test/java/org/finos/legend/depot/server/resources/TestPureModelContextDataResource.java, pom.xml
Update Engine, sdlc and protocols
=> Update Engine, sdlc and protocols

pom.xml
update Engine @ 4.89.0 and SDLC @ 0.197.0
=> update Engine @ 4.89.0 and SDLC @ 0.197.0

pom.xml
=> Update engine/sdlc versions

pom.xml
updating versions of legend engine and sdlc
=> updating versions of legend engine and sdlc

pom.xml
update to latest engine and sdlc versions
=> update to latest engine and sdlc versions
